---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Create a role that authorizes EC2 Access to S3 bucket"
Metadata:
  Version: 0.7
Parameters:
  RoleName:
    Type: String
Resources:

  RoleEC2toS3:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          -
            Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
        Version: "2012-10-17"
      RoleName: RoleName
    Type: "AWS::IAM::Role"
  RootInstanceProfile:
    DependsOn:
      - RoleEC2toS3
    Properties:
      Path: /
      Roles:
        - RoleEC2toS3
    Type: "AWS::IAM::InstanceProfile"
  S3SpecificPolicy:
    DependsOn:
      - RoleEC2toS3
    Properties:
      PolicyDocument:
        Statement:
          -
            Action:
              - "s3:*"
            Effect: Allow
            Resource:
              - S3BucketARN
              - "migration-bucket-${AWS::AccountId}/*"
        Version: 2012-10-17
      PolicyName: SpecificPolicyS3-architecture
      Roles:
        - RoleEC2toS3
    Type: "AWS::IAM::Policy"
